### ISSUE TITLE
wow. I wrote this code when I was 16.

### ISSUE THREAD

**Issue by gnudles** [richelbilderbeek/Corridor#1]
last month I recalled that project and added it to my github account. also updated the code a bit (I made a fix back then to enable alpha blending)
check this out.
https://github.com/gnudles/corridor
btw, It is so funny that I wrote it all in single file.

**Comment by richelbilderbeek** [comment]
Cool to meet the you @gnudles on GitHub!

Would you enjoy I merge my work (that is, adding a Qt Creator project and a Travis CI script) to your repo (by either Pull Request or you make me a Collaborator)?

 * No = fine
 * Yes = awesome

**Comment by gnudles** [comment]
I find it a bit strange to use Qt build system to a non-Qt project. But since I like Qt, and you already did it, then it is not bothering me that you add that as a build option. and adding Travis-CI is super. thanks. I will add you as contributer with joy.

**Comment by richelbilderbeek** [comment]
Awesome! Will happily do so :+1:

Note, you will need to activate Travis CI (at `travis-ci.org`) for your Corridor repo (it's free and you can use GitHub to log in), but it *is* something you (not me) need to do. Will you agree on that as well?

**Comment by gnudles** [comment]
I did it now. can you see?

**Comment by richelbilderbeek** [comment]
Awesome, I am in. Thanks! Will move my work before Sunday 23:59 :+1:

**Comment by gnudles** [comment]
take your time. :)

**Comment by richelbilderbeek** [comment]
@gnudles: I've merged my work with yours. I hope you like it. If not, feel free to modify according to your taste: you are the owner :+1: 

Closing this Issue :rainbow:

**Comment by gnudles** [comment]
thanks, great job!

**Comment by richelbilderbeek** [comment]
Thanks for letting me! And creating that cool game :+1:
